# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0004_order_orderdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order_Details'},
        ),
    ]
